### ISSUE TITLE
switch to using python-requests rather than python-httplib2

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClient#14]
The client currently requires the `python-httplib2` library.  This is only available from EPEL and requires that it be added to the yum configuration.  Moreover, the SSL handling within this library (should we ever use it) is poor.  The `python-requests` library is a part of the core CentOS distribution (not needing the EPEL repository) and handles SSL much more sensibly.

I would propose to switch from the httplib2 library to the requests library to minimise the repositories and improve the SSL handling.

**Comment by loomis** [comment]
The dynamic parts of the refactored run resources will use websockets or server sent events to eliminate polling for updated states/parameters.  To do this easily, moving from httplib2 to requests is required.

Migrate all of the python client/server code to requests. If possible, converge on the SlipStream Python API as a common library for interacting with the SlipStream server to isolate the low level interactions from the various clients.

**Comment by konstan** [comment]
Here is a bit of info on websockets in general and in Python https://www.fullstackpython.com/websockets.html

This is the client side implementation of websockets in Python 
https://github.com/websocket-client/websocket-client
It implements HyBI-13 (https://tools.ietf.org/html/rfc6455 which is apparently the latest one).  It’s to take this into account when selecting server side implementation.

There is nothing related to websockets in `requests`.

**Comment by konstan** [comment]
Stop working on introduction of `requests`.  
Instead work on introduction of websockets in #334.
Putting it back to `Ready for Work`.

**Comment by konstan** [comment]
Work on introduction of `requests` is done in `isssue_#14-requests` branch.

The work continues in the branch on implementation of client-side SSE #335
