### ISSUE TITLE
Create an Ubuntu-14.04 standalone image

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamClient#148]

**Comment by konstan** [comment]
What for?

**Comment by schaubl** [comment]
For nuv.la (`https://nuv.la/module/examples/images/`).
@anis-sixsq created `*-standalone` for all base images, so the idea was to do the same for the new Ubuntu 14.04.
`-standalone` images are like the corresponding base images but with a GUI and a VNC access.

**Comment by schaubl** [comment]
I would like to suggest to rename `*-standalone` components to `*-desktop` or `*-remote-desktop` or `*-vnc-desktop`.
Because when I see `standalone` I don't know what does it means and when I looked into the recipe I saw that it means, base image plus a Desktop with a VNC access.

**Comment by schaubl** [comment]
Currently the latest LTS version is 16.04 and it looks like desktop versions of base images are not used, so closing this issue.
