### ISSUE TITLE
Connectors should report sizes of the extra disks attached to VM

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#158]

**Comment by loomis** [comment]
Related to the collection of usage records.

**Comment by loomis** [comment]
May depend on libcloud so wait until after we've upgraded to the latest libcloud release.  SixSq/tasklist#378

**Comment by mebster** [comment]
Need to be extended to the following connectors:
- OpenStack
- CloudStack
- vCloud
- StratusLabIter
