### ISSUE TITLE
setting abort should truncate message if too long

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClient#184]
When high-level scripts fail in a deployment, the exception text will be pushed into the abort flag.  For very long exceptions (for instance when a large package installation fails), this will instead result in a 500 error from the server.  This bubbles up from this error in hibernate:
```
2015-10-19T09:46:40.907+0100 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions data exception: string data, right truncation
```
and appear to the end user in the reports as:
```
HTTP call error: ('Failed calling method PUT on url https://109.231.126.66/run/c38d52bf-822b-4367-903a-8942b885f9ce/orchestrator-Flexiant-c2:abort?ignoreabort=true, with reason: 500: Server Error',)
```
This makes finding the real reason the script failed more difficult and makes it seem as if it was a server error rather than a script error. 

The `fail` method in the `BaseWrapper.py` file should probably truncate the given message automatically to avoid the internal server error.  As the interesting bits of error messages are usually at the beginning and end, perhaps a "middle" truncation would be the best, but is probably more difficult to achieve than just a "left" or "right" truncation.

**Comment by schaubl** [comment]
This will be done Server side. See slipstream/SlipStreamServer#483
