### ISSUE TITLE
Machine executor should retry on getting run state

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#192]
Recently it was noticed that queries to `ss:state` may from time to time return an empty body.  To tolerate this, introduce the state request retry on the level of MachineExecutor:

https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/python/slipstream/executors/MachineExecutor.py#L58

**Comment by konstan** [comment]
Just seen this again while testing `nuv.la` after the upgrade.  

`ss:abort- Exception with detail: Machine executor: No state to execute specified.`

@loomis I'm suggesting to promote this issue to this sprint v2.20

**Comment by loomis** [comment]
Agree to promote it sprint v2.20.  We can discuss at the standup, who will take it and what to move out.
