### ISSUE TITLE
Revisit async launch of scripts during the bootstrap via ssh

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#193]
We scp `<script>` before launching it, then the options are:

- `at now -f <script>`
- `nohup <script> &`
- ignore `SIGHUP` in the `<script>` by adding `trap '' 1`

**Comment by schaubl** [comment]
After scp `<script>` we can also install the node executor service and then execute without nohup `service start slipstream-node/orchestrator`
