### ISSUE TITLE
use StratusLab Runner interface rather than OpenNebula Runner class

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClient#2]
The StratusLab client has been refactored to allow backward compatibility with previous StratusLab deployments while supporting the newer CIMI interface for new deployments.  

The SlipStream client relies directly on the Runner class for OpenNebula.  This will fail when StratusLab infrastructures deploy a newer StratusLab release.  The client should be refactored to use the interface and add a parameter to switch between which is active for a given infrastructure.

**Comment by konstan** [comment]
Closing.  Moved to https://github.com/slipstream/SlipStreamConnectors/issues/13
