### ISSUE TITLE
httplib2 is not installed automatically with client

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClient#203]
When installing the slipstream-client from pypi, the httplib2 library is not installed automatically.  This dependency should be added.

**Comment by konstan** [comment]
The dependency is there 

https://github.com/slipstream/SlipStreamClient/blob/master/pypi/src/main/python/setup.py#L78
https://pypi.python.org/pypi/slipstream-client/2.19.1 see `Requires`

however it's not picked up by pip.  Need to fix this.
