### ISSUE TITLE
User deployment script fails if an argument starts with '-'

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#207]
In this case a randomly generated password was provided to `ss-set`.  (From WordPress deployment).

```
+ ss-set mysql_password -qeKVog9SFhp
Usage: ss-set [options] <key> [<value>]

<key>            Key from which to set the value. Note that if the parameter
                 does not exist, the run will abort.
<value>          Value to be set.  This parameter is mandatory, unless the
                 --decrement option is uses, in which case this parameter is
                 ignored

ss-set: error: no such option: -q
```

Solution:

- update documentation for CLI and suggest using `--` for separation of `[options]` and arguments (right before the arguments after all options and parameters are already provided).

**Comment by schaubl** [comment]
It will not solve the issue.
To solve the issue the value should be surrounded by quotes.

Ex: 
```bash
ss-set mysql_password '-qeKVog9SFhp'
```
or
```bash
pass='-qeKVog9SFhp'
ss-set mysql_password "${pass}"
```

**Comment by konstan** [comment]
Yes, this might be an option.  Though in the second case you are missing double quotes `"` around `'-qeKVog9SFhp'` when defining or single ones when using it.  You want single quotes remain the part of the string you are providing to the CLI as the argument.  So,

```
pass="'-qeKVog9SFhp'"
ss-set mysql_password ${pass}
```
or 

```
pass=-qeKVog9SFhp
ss-set mysql_password "'${pass}'"
```

So, yes - something along this lines would work as well.

**Comment by konstan** [comment]
To support the initial "Solution" with `--` 
http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap12.html#tag_12_01
and yes @schaubl this looks to be in POSIX.2: https://en.wikipedia.org/wiki/POSIX#POSIX.2 as the 2001 year revision of POSIX.1 - `POSIX.1-2001 or IEEE Std 1003.1-2001` in `Commands and Utilities`.
