### ISSUE TITLE
When executing user targets give the corresponding script files meaningful names

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#216]
At the moment this is what user gets as the error message

`ss:abort- Failed running 'execute' target on 'master.1': /tmp/tmpcyUm7V: line 157: syntax error: unexpected end of file`

where the actual (bash) interpreter error points to some `/tmp/tmpcyUm7V` file, and this confuses users as it makes them think that this is an error somewhere from the framework and not from one of their scripts.

Here is the creation of the script as temporary file https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/python/slipstream/executors/MachineExecutor.py#L300

So, the suggestion is to name the scripts at least according to the target and recipe names

```
<targets>
  <target name="onvmremove">on vm remove</target>
  <target name="report">reporting</target>
  <target name="execute">deployment</target>
  <target name="onvmadd">on vm add</target>
</targets>
...
<prerecipe>pre-install</prerecipe>
<recipe>post-install</recipe>
...

```

or if not directly following their names on UI

- `/tmp/slipstream-Pre-install.sh` - `Pre-install` script
- `/tmp/slipstream-Post-install.sh` - `Post-install` script
- `/tmp/slipstream-Deployment.sh` - `Deployment` script
- `/tmp/slipstream-Reporting.sh` - `Reporting` script
- `/tmp/slipstream-On_Vm_Add.sh` - `On Vm Add` script
- `/tmp/slipstream-On_Vm_Remove.sh` - `On Vm Remove` script

Also, just noticed that `... running 'execute' target ...` is misleading as well.  Instead, it should be displayed `Deployment script` to better correspond to the UI definition.

**Comment by schaubl** [comment]
Now scripts are named with the following schema:
`<module_uri>__<script name>`
The script name correspond to the name displayed in the UI.
In the case the script fails, the name displayed in the UI will be used (eg: `Deployment` instead of `execute`).
