### ISSUE TITLE
publish initial clojure SlipStream client

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClient#221]
Integrate build of SlipStream client into full SlipStream build.  The code exists in branch `feature/clj-client`.

**Comment by konstan** [comment]
@loomis Please review and comment.  Thanks in advance!

Current location of the library https://github.com/slipstream/SlipStreamClient/tree/feature/clj-client

In the list below I'm in favour of the second option.

- [ ] keep the client in `slipstream/SlipStreamClient/clj-client`;
- [ ] extract into a separate public project `slipstream/clj-ss-client`.

The library is self-contained and has no dependencies on any of the existing SlipStream libraries.

At the moment the namespace/name is `com.sixsq.slipstream/clj-client`.  Unless you have a strong argument against this, I would keep it as is for now.

The project is a maven project and uses `clojure-maven-plugin`.

Irregardless of the code location, the build would create RPM named `slipstream-client-clojure`.  It will contain one file -- uberjar `/opt/slipstream/downloads/clj-ss-client.jar`.  The jar will be used by orchestrator with the scaling capabilities.  The orchestrator would download the file to `/opt/slipstream/client/lib` and provide it to the `riemann` on the class path.

When the client gets extended and new usages are found, we can provide other packaging options, distribution and deployment locations.

**Comment by loomis** [comment]
I'd also prefer to put this into a separate repository.  However, I'd prefer a name that is language independent and follows the existing naming scheme.  Perhaps, "slipstream/SlipStreamClientAPI" will work? 

After the repository is created, it needs to be added to the Bootstrap and built as part of the normal, complete build.  I can do that part once we agree on the repository name.

**Comment by konstan** [comment]
Agreed with `slipstream/SlipStreamClientAPI`.  
I propose the following structure and hope it works with Bootstrap.
```
.
|____clj-ss-client
| |____pom.xml
| |____project.clj
| |____rpm
| |____src
| |____test
|____pom.xml
```
Please let me know if this is OK -- then, I can add the repo and migrate the code there.

**Comment by loomis** [comment]
I think that you can flatten the structure and just put the contents of the clj-ss-client module at the top level.

**Comment by konstan** [comment]
OK.

**Comment by konstan** [comment]
The library is now published with the code in the new repo https://github.com/slipstream/SlipStreamClientAPI

**Comment by konstan** [comment]
Added https://github.com/slipstream/SlipStreamClientAPI to Bootstrap (community and enterprise).
