### ISSUE TITLE
Running 'packages' target on Ubuntu may fail on apt-get update with 'W: Failed to fetch ... Hash Sum mismatch'

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#222]
The issue and workarounds are described in http://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error

We need to see if suggested cleanup 
```
rm -rf /var/lib/apt/lists/*
mkdir /var/lib/apt/lists/partial
``` 
works for us.  It should be done conditionally when this particular failure is detected. 

Also, there is a suggestion of waiting for sometime and retry.  
Also, changing the URL of the archive can be considered (e.g., `http://ch.archive.ubuntu.com -> http://us.archive.ubuntu.com (or de, fr etc.)`

**Comment by mebster** [comment]
Do we know why this happens?

**Comment by schaubl** [comment]
This is because race condition in apt-get repository.
It might happens for example if repositories are not synced which can happens if there is some cache-proxy.

**Comment by konstan** [comment]
The same change has to be implemented in slipstream bootstrap for Ubuntu.
https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/scripts/slipstream.bootstrap.py#L263
I see similar issue now on Exoscale with orchestrator.

**Comment by schaubl** [comment]
@konstan: We can do something like this 
```python
cmd = 'export DEBIAN_FRONTEND=noninteractive; (apt-get -y update || rm -rf /var/lib/apt/lists/* && mkdir -p /var/lib/apt/lists/partial && apt-get -y update); apt-get -y install'
```
here [slipstream/util.py line 626](https://github.com/slipstream/SlipStreamClient/blob/v2.21-community/client/src/main/python/slipstream/util.py#L626).

**Comment by konstan** [comment]
Yes, looks OK, with an exception of needing to wrap the set of commands after the `||` into `{}`.

```
cmd = 'export DEBIAN_FRONTEND=noninteractive; (apt-get -y update || { rm -rf /var/lib/apt/lists/* && mkdir -p /var/lib/apt/lists/partial && apt-get -y update; }); apt-get -y install'
```
We can also check if in the case of a failure the output contains `Hash Sum mismatch` and only then manipulate the `lists/` dirs.

For slipstream bootstrap, the chosen implementation has to be copied from the `utils.py`.

**Comment by konstan** [comment]
This is happening now on Exoscale when attempting to provision SS for demo.
```
root@orchestrator-exoscale-ch-gva8ba-b5c-1f9c-4c68-95b3-6681fcebbd31:~# date
Fri Feb 12 14:13:42 UTC 2016
root@orchestrator-exoscale-ch-gva8ba-b5c-1f9c-4c68-95b3-6681fcebbd31:~# /usr/bin/apt-get -y update
Ign http://ch.archive.ubuntu.com trusty InRelease
Hit http://ch.archive.ubuntu.com trusty-updates InRelease
Hit http://ch.archive.ubuntu.com trusty Release.gpg
Hit http://ch.archive.ubuntu.com trusty-updates/main Sources
Hit http://ch.archive.ubuntu.com trusty-updates/universe Sources
Hit http://ch.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://ch.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://ch.archive.ubuntu.com trusty Release
Get:1 http://ch.archive.ubuntu.com trusty-updates/main amd64 Packages [696 kB]
Hit http://security.ubuntu.com trusty-security InRelease
Get:2 http://ch.archive.ubuntu.com trusty-updates/universe amd64 Packages [336 kB]
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://ch.archive.ubuntu.com trusty/main Sources
Hit http://ch.archive.ubuntu.com trusty/universe Sources
Hit http://ch.archive.ubuntu.com trusty/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://ch.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://ch.archive.ubuntu.com trusty/main Translation-en
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://ch.archive.ubuntu.com trusty/universe Translation-en
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Ign http://ch.archive.ubuntu.com trusty/main Translation-en_US
Ign http://ch.archive.ubuntu.com trusty/universe Translation-en_US
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Fetched 1,032 kB in 2s (426 kB/s)
W: Failed to fetch http://ch.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://ch.archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@orchestrator-exoscale-ch-gva8ba-b5c-1f9c-4c68-95b3-6681fcebbd31:~#
```

**Comment by konstan** [comment]
The proposed solution is not helping.

```
root@orchestrator-exoscale-ch-gva8ba-b5c-1f9c-4c68-95b3-6681fcebbd31:~# rm -rf /var/lib/apt/lists/*
root@orchestrator-exoscale-ch-gva8ba-b5c-1f9c-4c68-95b3-6681fcebbd31:~# mkdir /var/lib/apt/lists/partial
root@orchestrator-exoscale-ch-gva8ba-b5c-1f9c-4c68-95b3-6681fcebbd31:~# /usr/bin/apt-get -y update
Ign http://ch.archive.ubuntu.com trusty InRelease
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
...
Ign http://ch.archive.ubuntu.com trusty/universe Translation-en_US
Fetched 22.7 MB in 6s (3,653 kB/s)
W: Failed to fetch http://ch.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://ch.archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@orchestrator-exoscale-ch-gva8ba-b5c-1f9c-4c68-95b3-6681fcebbd31:~#
```

**Comment by konstan** [comment]
Next attempt is to try to change the archive.

**Comment by konstan** [comment]
Created a ticket on Exoscale https://portal.exoscale.ch/tickets/1009321

**Comment by konstan** [comment]
Exoscale is following this up with Canonical.  At the same time, Exoscale is promising to implement a caching proxy w/o this issue on their side.

On Mar 14, 2016 9:17
```
Hello,

Unfortunately, the problem is said to be expected by Canonical. There is a short period of time during which the mirror is inconsistent. It should not last over a couple of minutes. We plan to propose our own mirrors which will not expose this problem.

```

**Comment by konstan** [comment]
Latest reply from Exoscale.

```
Hello,

After a few tests, it seems that "de.archive.ubuntu.com" is more reliable than "ch.archive.ubuntu.com". You could do "sed -i s/ch.archive/de.archive/ /etc/apt/sources.list" as a temporary workaround. We continue to monitor the situation a bit and we may switch our images to use de.archive.ubuntu.com in the future. If you are using cloud-init, you can also use:


system_info:
package_mirrors:
- arches: [i386, amd64]
failsafe:
primary: http://de.archive.ubuntu.com/ubuntu
security: http://security.ubuntu.com/ubuntu

```

**Comment by konstan** [comment]
@schaubl can we extend cloud-init metadata on `exoscale` connector? Otherwise, we do the manual change in `slipstream.bootstrap` for Exoscale only.

**Comment by schaubl** [comment]
Currently we pass our contextualization script to cloud-init via the `user-data`.
If we want to pass both our contextualization script and some cloud-init instructions, we have to package these two as `multipart-data` and put them into the `user-data`.

This can be implemented in the connector. The function `_get_bootstrap_script` has to be reimplemented.

**Comment by mebster** [comment]
Will this work with all connectors on all clouds?

**Comment by konstan** [comment]
At the moment there is the same issue with deac cloud.  We can apply the prosed change to "de.archive.ubuntu.com" from the currently used "lv.archive.ubuntu.com".  In case we want to cover "all the clouds" we definitely need to do this in the `slipstream.bootstrap`.

**Comment by schaubl** [comment]
@mebster Possibly yes. This method can be redefined in any connector. But not all Cloud connectors makes uses of Cloud-Init.

Deac (vCloud) for example doesn't use cloud-init.

**Comment by schaubl** [comment]
We also have to ensure that the German mirror is more stable.

**Comment by konstan** [comment]
So, basically the common denominator solution is to switch between different archives and hope that others are in sync.  And this was proposed at the very beginning.  So, no progress on fixing the real issue.

Lets schedule and implement the heuristics of selecting different archives (in case of failures).  Agreed?

**Comment by konstan** [comment]
Implementation in `slipstream.bootstrap` for Ubuntu and on all clouds.

**Comment by konstan** [comment]
And while we are fixing this, @loomis suggests to switch to centos 7 for Orch on all clouds.  
centos 7 should boot very fast now.

**Comment by konstan** [comment]
On `Thu Mar 31 15:52:15 CEST 2016` Exoscale closed ticket https://portal.exoscale.ch/tickets/1009321 with

```
Hello,

Our Ubuntu images have been updated to use de.archive.ubuntu.com instead of ch.archive.ubuntu.com.
```
