### ISSUE TITLE
creation of slipstream_managed security group fails on processing input

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#225]
Deployment fails with `"ss:abort - 'list' object has no attribute 'strip'"`
Security group is the list not a string. 
https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L374

Fix
```python
       for ni in nodes_instances.itervalues():
            sgs = map(lambda x: x.strip(), ni.get_cloud_parameter(sg_key, ''))
            if sg_name in sgs:
                self._create_allow_all_security_group()
                break
```

**Comment by schaubl** [comment]
@konstan: Can you explain your exact case (connector, type of run, ...)?
AFAIR : security group is a string which contain a csv list.

**Comment by konstan** [comment]
@schaubl this is what I'm checking now to add to the issue.

**Comment by konstan** [comment]
This is ~okeanos connector.
https://github.com/CELAR/SlipStreamConnector-Okeanos/blob/master/python/tar/slipstream_okeanos/OkeanosRunInstancesCommand.py#L26

I can easily update the connector code not to split on commas.  However, IMHO the programmatically more sound approach would be to have a list on the NodeInstance object.  Any objections?

**Comment by schaubl** [comment]
This is already done with the method [`NodeInstance.get_security_groups`](https://github.com/slipstream/SlipStreamClient/blob/v2.22-community/client/src/main/python/slipstream/NodeInstance.py#L171).
This is why on the method [`BaseCloudConnector.__create_allow_all_security_group_if_needed`](https://github.com/slipstream/SlipStreamClient/blob/v2.22-community/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L374) I used [`NodeInstance.get_cloud_parameter`](https://github.com/slipstream/SlipStreamClient/blob/v2.22-community/client/src/main/python/slipstream/NodeInstance.py#L63)

**Comment by konstan** [comment]
I see a problem here: two ways of getting the attribute that return different results.  
What about storing as list and using the specific getter for the attribute (`NodeInstance.get_security_groups()`) here as well [BaseCloudConnector.__create_allow_all_security_group_if_needed](https://github.com/slipstream/SlipStreamClient/blob/v2.22-community/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L374)
especially as I see that `NodeInstance.get_security_groups()` strips the strings.  OK/NOK? :)

**Comment by schaubl** [comment]
@konstan: I was trying to reply but my message would be too complicated and too long.
Can we discuss it on Monday in the office ?

**Comment by konstan** [comment]
Yes, sure.

**Comment by konstan** [comment]
Because there multiple ways to get the same attribute, briefly my idea is to store the values in the way they are expected to be obtained.  So, all ways of setting an attribute in (https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/python/slipstream/NodeInstance.py) would filter and transform the values if needed.
