### ISSUE TITLE
fast clients can fail run due to inconsistent state of scale.state RTP

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#230]
The exception below 
```
Exception with detail: Inconsistent scaling situation. 
Single scaling action allowed, found: 
{'removing': ['testvm.1', 'testvm.3'], 'created': ['testvm.2']}
```
was raised by Orch after transiting to *Provisioning* in scale down action (for instances `1` and `3`) immediately after reaching *Ready* in previous scale up (for instances `2` and `3`).  Similar errors are seen on different stages of "fast" scale up/down cycles from "fast" clients, which request the next scale action immediately after they see the run reaches *Ready*.

In the case above the values of the `scale.state` per instance should have been: `testvm.1 == removing`, `testvm.2 == operational`, `testvm.2 == removing`.  See PS: regarding the consistency check.

The problem disappears after introducing couple of second sleeps on the client side when *Ready* state gets detected.

It looks as if the issue is due to `scale.state` RTP not on all of the component instances gets set before the transition to *Provisioning* happens and when it gets queried by Orch to decide on the required action.

Solution:
 -  on `NodeDeploymentExecutor`, move setting of the `scale.state` to `operational` from [`onReady()`](https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/python/slipstream/executors/node/NodeDeploymentExecutor.py#L137) to the every end of `onSendingReports()`.  This ensures that when run transits to `Ready` the `scale.state` will be consistent on all of the component instances, due to the global synchronisation in the `SendingReports` state (`completed` RTP gets always set after all of the `on*()` state execution methods).

PS:
`scale.state` RTP of component instances is used by Orch to decide what VM IaaS operations to apply on the instance.  `scale.state` RTP has it's own state machine - see https://github.com/SixSq/tasklist/issues/268  `Node instance RTP scale.state values mapped on State Machine`.  Possible values in scalable run `scale.state == <creating|created|*operational*|removing|removed|*gone*|resizing|resized|disk_attaching|disk_attached|disk_detaching|disk_detached>`

When Orch enters *Provisioning* state it checks if all VMs that are not in `operational` or `gone` states have the same `scale.state`.  This check is done to provide consistency when scaling the application via altering its various component classes.  And this follows the current design of the scalable run.

**Comment by konstan** [comment]
@schaubl Do you know of any downsides of the proposed solution?  Thanks.

I'll apply this solution in a branch and test it.

**Comment by konstan** [comment]
The fix is pushed to https://github.com/slipstream/SlipStreamClient/compare/issue_%23230-consistent-scale-state

**Comment by schaubl** [comment]
> Do you know of any downsides of the proposed solution?
No
