### ISSUE TITLE
use full URIs of the app components when logging

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#252]
There was the following hierarchy: `centos-7 <- comp1 <- comp2 <- centos-7`.  The log refers to centos-7 in both cases and it's confusing.  Also, there might be errors/confusions when greping through the logs.

```
: 2016-03-24T14:22:09Z : Executing build recipes 
: 2016-03-24T14:22:10Z : Nothing to do on target: centos-7.prerecipe 
: 2016-03-24T14:22:10Z : 
==== Executing target 'comp1.prerecipe'

: 2016-03-24T14:22:10Z : Calling: /tmp/tmpMp2XqQpre-install comp1
 
: 2016-03-24T14:22:10Z : End of the target script 
: 2016-03-24T14:22:10Z : 
==== Executing target 'comp2.prerecipe'

: 2016-03-24T14:22:10Z : Calling: /tmp/tmpCYGtiYpre-install comp2
 
: 2016-03-24T14:22:10Z : End of the target script 
: 2016-03-24T14:22:10Z : 
==== Executing target 'centos-7.prerecipe'

: 2016-03-24T14:22:10Z : Calling: /tmp/tmppo10Xupre-install centos-7
 
: 2016-03-24T14:22:10Z : End of the target script 

```

I labeled it `Ready to work`.  Feel free to disagree or reassign.

**Comment by schaubl** [comment]
It's easy to do but I personally prefer them like it is now (of course because I did it like this :stuck_out_tongue_winking_eye: ).

I would suggest to ask to others their opinion.

@slipstream/crew @slipstream/owners ?

BTW it's a good opportunity to try "reactions"

**Comment by mebster** [comment]
My 50 cents...

The tmp filename always bothered me.  I think it should have a name like:
<index>-<app-comp>-<target>

The <index> would indicate the order in the hierarchy and correspond to the order of execution of the scripts.

@konstan in your example you have centos7 twice. Why?  It looks like a circular dependency.

**Comment by konstan** [comment]
@mebster regarding the file names here is the issue https://github.com/slipstream/SlipStreamClient/issues/216  Now, with the inheritance in hand it should be updated, by probably adding component name to the script.  And this is where the above issue with hit us.
---

I just didn't know that the name of the one of the components in the inheritance tree was named `centos-7`.  And it just happened that I called one of mines `centos-7` as well and the "system" didn't correct me ;)

**Comment by mebster** [comment]
Should we then use the fully qualify app comp name in the file?

**Comment by konstan** [comment]
In the same vein of improving the logging. 
The log below is already from an application deployment, where the app component (node in the deployment) was named `comp3` (the actual component name is `comp2`).

```
==== Executing target 'comp2.execute'

: 2016-03-24T16:15:22Z : Calling: /tmp/tmpN0D6kAdeployment comp2
/tmp/tmpN0D6kA: line 4: comp1-param=comp1-param: command not found
 
: 2016-03-24T16:15:33Z : End of the target script
: 2016-03-24T16:15:33Z : 
ERROR: Failing... Failed running 'comp2.execute' target on 'comp3.1': /tmp/tmpN0D6kA: line 4: comp1-param=comp1-param: command not found
None
```
The error message for the failure is OK.  But I would update `Executing ...` to

```
==== Executing target 'comp2.execute' on 'comp3.1'
```

And probably even

```
==== Running '<project>/<component-name>' deployment script on '<other-project>/<app-component-name>.<id>'
```

And of course, `deployment` there changes depending on the target (`pre-install`, `post-install`, `on-vm-add`, `on-vm-remove`, etc.).  I.e. clearly corresponds to the name on the UI (#216).
