### ISSUE TITLE
ss-get keys

### ISSUE THREAD

**Issue by WinstonSureChill** [slipstream/SlipStreamClient#259]
Is it possible to have a list of all the keys that can be used for `ss-get`?

At first I was thinking only the keys defined in the "Application Parameters" section could be used (i.e. `hostname` & `instanceid` by default), but it appears we can also use key `multiplicity`, which doesn't seem to be defined anywhere.

**Comment by mebster** [comment]
It's an open schema. In principal, all parameters in the run are available. This includes the default parameters, but also the user defined parameters.  Here's an example from the LAMP demo app.
![screen shot 2016-04-01 at 13 28 05](https://cloud.githubusercontent.com/assets/419519/14205735/d7c07e9c-f80d-11e5-85af-a40070c5367b.png)

**Comment by konstan** [comment]
`ss-get` works with so called run-time parameters (RTP).  There are three types of them
- component RTP: `lb:ids`, `lb:multiplicity` etc.
- component instance RTP: `lb.1:ready`, etc.
- global RTP in `ss` namespace: `ss:abort`, `ss:status` etc.

**Comment by WinstonSureChill** [comment]
Stupid me! Sorry for the dumb question ha ha
