### ISSUE TITLE
Provide tags as a runtime parameter

### ISSUE THREAD

**Issue by WinstonSureChill** [slipstream/SlipStreamClient#260]
Tags don't seem to be provided as a runtime parameter. I would like to be able to retrieve them with `ss-get`. I think it is possible to retrieve them with `ss-run-get`, but it requires authentication, and I want to avoid writing passwords in clear-text in Deployment scripts.

**Comment by mebster** [comment]
What use case do you have in mind?

**Comment by konstan** [comment]
Have you tried `ss-get ss:tags`?

**Comment by WinstonSureChill** [comment]
Nope, didn't try it. Imma do it right now!

**Comment by WinstonSureChill** [comment]
@mebster the use case is that we have multiple deployments connecting to the same DNS machine (SkyDNS). Thus, we want to create different SkyDNS namespaces, based on Slipstream run tags, so that different components don't step on each other.

**Comment by mebster** [comment]
Ok, thanks
