### ISSUE TITLE
scripts in /tmp are cleared on reboot

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClient#265]
If the user performs a reboot as part of the post-install script (e.g. to ensure the most current kernel version), the SlipStream script are removed because CentOS 7 (and maybe others) clears out `/tmp` after a reboot.  This causes problems after the reboot.  

Probably moving the script to a safe place is the easiest solution.

**Comment by schaubl** [comment]
Now script files goes into `/var/lib/slipstream` with a fallback to `/var/tmp/slipstream` if it's not possible (like if we don't have enough permissions) and for Windows scripts goes into the `%AppData%/slipstream` folder.
The working directory of the scripts is `/var/tmp/slipstream`
