### ISSUE TITLE
*-run-instance fail because of missing slipstream.context file

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamClient#271]
On NuvlaBox, I have to create a slipstream.context file in /root/slipstream.context with following content `[contextualization]`. This issue appear from version 3.0 or 3.1
And from version 3.2 I have to create this file in /opt/slipstream/client/sbin and in /opt/slipstream/client/bin manually and no more in /root to be able to start a run or a deployment.

**Comment by schaubl** [comment]
@konstan: Is it fixed ?

**Comment by schaubl** [comment]
duplicate of #254
