### ISSUE TITLE
configuration files must not be required for build

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClient#277]
Currently, two configuration files are required to build the SlipStream software.  This is wrong; the build must not depend on outside configuration. 

The following is the text from the contributors guide concerning these files:
```
$ touch /usr/bin/slipstream.client.conf

$ cat > ~/slipstream.context << EOF
[contextualization]
diid = 123
cookie = foo
serviceurl = http://example.com
node_instance_name = instance-name
EOF
```

**Comment by loomis** [comment]
The `slipstream.context` file no longer appears to be needed for the build.

**Comment by konstan** [comment]
`slipstream.context` is still need for the build.  Opened #282
