### ISSUE TITLE
Update libcloud from v0.18.0 to v2.2.1

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamClient#295]

**Comment by loomis** [comment]
libcloud v1.1.0 has been uploaded to nexus.

**Comment by loomis** [comment]
Note that libcloud v1.1.0 does not contain the "Migrating" state for CloudStack.  Exoscale folks have submitted a PR request for this (https://github.com/apache/libcloud/pull/847), which has been merged. It will likely show up in the next patch release.

**Comment by 0xbase12** [comment]
Libcloud version we use is to old and hot patched from everywhere. It doesn't work with latest versions of python 2.7.
We got issue while upgrading Nuvla to v3.38. This also making some orchestrator to not work properly.

**Comment by loomis** [comment]
The current driver (v3.54) when installed with pip forces a user's system to downgrade from recent apache-libcloud releases to 0.18.0.  The Exoscale driver does not work correctly in this version and the user is left with a broken installation and error messages that give no clue as to what is wrong.

**Comment by schaubl** [comment]
We should upgrade to the latest version or stop using libcloud.

Currently AFAIK there is only the CloudStack and OpenStack connectors which makes use of libcloud.
- The OpenStack connector could reuse the work done in the OTC connector to get rid of libcloud.
- There is only the CloudStack connector left but it can also quite easily be rewritten without libcloud because I already have some code to make use of the CloudStack API without libcloud.
