### ISSUE TITLE
Python2.x only client happily installs under Python3.x with pip and then fails when used

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#306]
```
$ pip show slipstream-client | grep Location
Location: /usr/local/lib/python3.5/site-packages
$ ss-set --help
Traceback (most recent call last):
  File "/usr/local/bin/ss-set", line 21, in <module>
    from slipstream.command.CommandBase import CommandBase
  File "/usr/local/lib/python3.5/site-packages/slipstream/command/CommandBase.py", line 70
    print '\nExecution interrupted by the user... goodbye!'
                                                          ^
SyntaxError: Missing parentheses in call to 'print'
$
```

Related to https://github.com/SixSq/tasklist/issues/1012

**Comment by konstan** [comment]
The problem was that my default pip was pointing to python3.5 interpreter in its header.  However, potentiall when `python_requires='>=2.6,<3.0'` is used with `setuptools.setup()` the installation should not install the package under python3.x.  https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords

Checked this with `SlipStreamPythonAPI` project, however it looks like the `python_requires` is not respected.  Digging further.

**Comment by 0xbase12** [comment]
Is this ticket done? If yes I'll put v3.24 milestone and close it
