### ISSUE TITLE
support debian package installation

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClient#353]
Package installation on debian isn't supported at the moment. 

See https://github.com/slipstream/SlipStreamClient/blob/fb66a8c0bf0a34f1a64594beb8fb0f34cbb98f35/client/src/main/python/slipstream/util.py#L73

**Comment by loomis** [comment]
![error message](https://user-images.githubusercontent.com/490506/31267214-9b13d1b0-aa77-11e7-84e8-f750bf0fe0c1.png)

**Comment by schaubl** [comment]
Fixed in 6ba41577a9a03a6f5adb2eefabc79f9da7bf7e5b
