### ISSUE TITLE
image builder on StratusLab should fail the build if new image ID wasn't recovered

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#38]
On StratusLab the new image ID is searched in PDisk. If it's not found, Orch. should fail the build.

At the moment, in the case of such failure, the global state is Terminal and the Node pictograms are green.

![screen shot 2014-03-27 at 09 36 26](https://cloud.githubusercontent.com/assets/353767/2535219/12f1f080-b58b-11e3-8f06-68bfda12877f.png)

**Comment by loomis** [comment]
Connector is being discontinued.  Enhancements/fixes will not be made.
