### ISSUE TITLE
getting run by executors should use random delays and be a function of the component multiplicity

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#386]
Before getting the run node executor should get its component's multiplicity, multiply it by X to get the range for the wait time.  X is an average time to get an application run as XML with a single component and multiplicity 1.
This is to reduce the load on SS (especially in the case of scaling the runs).

**Comment by loomis** [comment]
@konstan @0xbase12 What's the status of this ticket and PR?  Is this change not necessary after the changes in the nginx configuration?

**Comment by 0xbase12** [comment]
IMHO, the random delay is no more necessary after changing nginx configuration and adding cache key.
It's even better that all nodes get the run at the same time, because it will be done one time by SS and retrieved from the nginx cache for all nodes getting the run in the 30 [s] time window.

**Comment by loomis** [comment]
Closing...
