### ISSUE TITLE
cannot run image with ss-execute

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClient#97]
The command `ss-execute` produces an error when trying to an image module.  The error is:
```
$ ss-execute -u sixsq_dev -p xxxx \
                       --endpoint=https://slipstream.sixsq.com  \
                       SlipStream/slipstream

Error: 
Module validation failed: com.sixsq.slipstream.persistence.ImageModule cannot be cast to com.sixsq.slipstream.persistence.DeploymentModule
```

**Comment by schaubl** [comment]
Currently this command can only run deployments or build image.

**Comment by 0xbase12** [comment]
Tested with following command:
*Launch service testing :*
```ss-execute --nagios -w 40 -u $user -p $pass --parameters=testclient:cloudservice=exoscale-ch-gva,apache:cloudservice=exoscale-ch-gva --endpoint=https://185.21.196.215 examples/tutorials/service-testing/system```

*Launch wordpress simple run :*
```ss-execute --nagios -w 40 -u $user -p $pass --parameters cloudservice=exoscale-ch-gva,admin_email=test@t.com --endpoint=https://185.21.196.215 apps/WordPress/wordpress```

We have to update nagios test script :
Never use simple quote with python optargs to pass string. If you use simple quote, the quote will be part of passed string and will be escaped!!
```/usr/bin/ss-execute --nagios -w 40 -u $ARG1$ -p $ARG2$ --parameters "testclient:cloudservice=$ARG3$,apache:cloudservice=$ARG3$" --endpoint 'https://$HOSTADDRESS$' "examples/tutorials/service-testing/system"```
