### ISSUE TITLE
Update the SlipStream examples in this repository with the latest one

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamClient#99]
At the same time I will do the following tasks:
- [x] Cleanup projects in `/apps` and in `/examples/tutorials`
- [x] Find the right place to store these SlipStream apps
- [ ] ~~Add links to the app website in the description~~ (see comment below)
- [x] Check and fix "owner"
- [x] Check and fix "rights" of Modules
- [x] Add modules into a Project
- [x] Remove unneeded Deployment
- [x] Include Module logo in SlipStream static-content
- [ ] Extract packages installation to the Package tab (not fully done)
- [ ] Extract corresponding part of the scripts to the recipe and prerecipe scripts. (not fully done)
- [ ] ~~Remove some deployment parameter and replace them with auto-generated values~~ (not enough time to be done)
- [x] Review and update documentation

**Comment by schaubl** [comment]
I will not `add links to the app website in the description` because the description will be too long and the link will not work.
We have to find an other place to put this link (in the notes maybe).

**Comment by sixsq-hudson** [comment]
Yes we could extend the note to include a field for external link, with a regex to validate and avoid code injection.

**Comment by schaubl** [comment]
See slipstream/apps#4
